name: 'Deploy Infrastructure with Terraform'

on:
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }} # IMPORTANT: Use an IAM Role for security
          aws-region: us-east-1 # Change to your desired region

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0

      - name: 'Terraform Init'
        id: init
        run: terraform init
        working-directory: ./infrastructure

      - name: 'Terraform Plan'
        id: plan
        run: terraform plan -no-color -out=tfplan
        working-directory: ./infrastructure
        continue-on-error: true

      - name: 'Terraform Apply'
        if: steps.plan.outcome == 'success'
        run: terraform apply -auto-approve -no-color tfplan
        working-directory: ./infrastructure
